# Generated by Django 5.1.7 on 2025-04-15 20:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_reminder_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='time'),
        ),
    ]
